### ISSUE TITLE
Question: whos updates are we supposed to download updates from?

### ISSUE THREAD

**Issue by LordNex** [dodexahedron/SE-Community-Mod-API#1]
Im not really a programmer or very use to this site or how it works. But I want to keep my dedicated server up and running. Who do we pull our downloads from and how do we keep our servers up to day when several people are writing for this now? Sorry, I know computers but im not a programmer by any means. Thanks in advance!

**Comment by dodexahedron** [comment]
That's a really complex question with a really complex answer.
It depends on what you want, really.
Could you perhaps narrow down for me what it is you're looking for most in the platform?

**Comment by LordNex** [comment]
Well for the most part I use it for the essentials plugin for grid management and other features. I also use the blueprint function. I'm just not sure where to pull the main downloads from if all of you guys are now working on it. Normally I just goto Tyrsis account and pull from the releases there.

**Comment by dodexahedron** [comment]
Continue to pull it from Tyrsis, then. We will be merging the changes upstream to there, anyway.

**Comment by dodexahedron** [comment]
SESE has been merged upstream.
Be sure to grab this build of Essentials, though, to work with that version of SESE:
https://github.com/dodexahedron/EssentialsPlugin/releases/tag/v1.0.2.1669-alpha
