### ISSUE TITLE
SESE Not Loading Plugins

### ISSUE THREAD

**Issue by LordNex** [dodexahedron/SE-Community-Mod-API#5]
I tried downloading a full copy of your SESE and Essentials on my server. I can run the SESE normally but it doesn’t recognize any plugins. I ended up going back to Tyrsis’s last release of SESE and your version of Essentials.  Which seems to run well. I didn't grab the logs at the time but I can try again and post them if you'd like. There were no errors in the main screen and just seemed to skip over them when scanning the Mods directory. I'm only running Essentials and Blueprints with SESE and they are all installed and seen by Tyrsis's Fork of SESE. Obviously Blueprints is still down until Ty decides to release his code or takes the time to fix it. Anyway, Just thought id let you know. Thanks

**Comment by dodexahedron** [comment]
Did you also use my fork of essentials?

-----Original Message-----

**Comment by LordNex** [comment]
Yes both

**Comment by dodexahedron** [comment]
I'll post the version in use on our server, which seems to work fine.

-----Original Message-----

**Comment by dodexahedron** [comment]
New version of Essentials has been posted.
Let me know if that works for you.
I can't guarantee compatibility with the blueprints mod, as I don't have source for that.
