### ISSUE TITLE
Multi Instance Log problem

### ISSUE THREAD

**Issue by emawind84** [dodexahedron/SE-Community-Mod-API#9]
Problem with more than one instance of SESE.
In some early release the log was in the world save folder but now is in the DedicatedServer64 and cause quite a problem for me, I can't use more than one instance without getting these exceptions.

![se_issue01](https://cloud.githubusercontent.com/assets/5586300/6639861/79c52966-c9d6-11e4-8de3-5572b9c90d70.gif)

I have two SE instances, discoworld and discoworld_survival; discoworld_survival is looking for SpaceEngineers-Dedicated.cfg in the folder discoworld when it should read the file inside discoworld_survival folder.

![se_issue02](https://cloud.githubusercontent.com/assets/5586300/6640226/27af49ce-c9d9-11e4-8046-3e7a2b95f908.gif)

Here you can see how I made the link for SE on the left and the start of the process on the right
![se_issue03](https://cloud.githubusercontent.com/assets/5586300/6640302/b9952b60-c9d9-11e4-8422-7c8f9751216a.gif)

The log should not be here I think but in the instance folder.
![se_issue04](https://cloud.githubusercontent.com/assets/5586300/6640353/155865ca-c9da-11e4-88d1-c34490362899.gif)

**Comment by dodexahedron** [comment]
Agreed that's not a good thing.
The behavior is inconsistent on my machine, but nobody has complained until now, so I hadn't bothered looking into it yet.
I'll have a look as soon as I can.
Until then, if you copy your SpaceEngineers folder and run each instance from a unique folder, you'll at least be able to get back up and running.

**Comment by emawind84** [comment]
I didn't think about that thank you I'll try.

**Comment by dodexahedron** [comment]
I'll try to have a look at why this is happening, tonight.
I've been considering ditching the logs as they are, anyway, and using nlog or something more configurable/standard, anyway.  Maybe this will be the motivation I need to go ahead and bite the bullet and do that.

**Comment by dodexahedron** [comment]
I'm just too beat to get too into tracing how the log paths are figured out, tonight.
I'm thinking I'm going to go ahead with a conversion to nlog.  Then you'll be able to log whatever you want to wherever you want.
Making it multi-instance friendly won't be THAT hard, but it may require a small amount of configuration on your part.  We'll see what I end up with.

**Comment by emawind84** [comment]
Thank you for your support on this project.

**Comment by dodexahedron** [comment]
I've been working on replacing the logging system with nlog.
So far, it's going well.
There are just a lot of places it needs to work, and work correctly.
I don't think it will be ready for this thursday's update, since I just don't have the time to do it before then, but good progress is being made.
Stay tuned.

**Comment by dodexahedron** [comment]
#11 is complete, which should also take care of this.
If you have issues with the new logging system, please open a new issue and give me as much detail as you can.
